### ISSUE TITLE
Move documentation from Codeplex to Github

### ISSUE THREAD

**Issue by anandtpatel** [dennisdoomen/CSharpGuidelines#62] opened 2017-06-03 11:26 UTC
Codeplex is sun setting Dec 2017. I noticed that download link for document take you to codeplex.

Also, Please move HTML document as documentation in github so easy for user to read.

**Comment by dennisdoomen** [comment] 2017-06-06 05:57
> Codeplex is sun setting Dec 2017. I noticed that download link for document take you to codeplex.

Need to find a new landing page for that. The ads pay for my domain names ;-)

> Also, Please move HTML document as documentation in github so easy for user to read.

What do you mean with that?

**Comment by dennisdoomen** [comment] 2017-11-13 18:02
Duplicate of #24

**Closed by dennisdoomen** 2017-11-13 18:02 UTC
