### ISSUE TITLE
Change link from csharpcodingguidelines.com to the GitHub repo

### ISSUE THREAD

**Issue by Mackiovello** [dennisdoomen/CSharpGuidelines#128] opened 2017-11-06 16:10 UTC
The link www.csharpcodingguidelines.com goes to a page that asks the user to go to this repo. It would be better to add a link directly to https://github.com/dennisdoomen/CSharpGuidelines instead.

**Comment by dennisdoomen** [comment] 2017-11-06 16:26
It used to go to CodePlex, because the ads pay for the DNS bills ;-)

**Comment by dennisdoomen** [comment] 2017-11-13 18:01
Duplicate of #24

**Closed by dennisdoomen** 2017-11-13 18:01 UTC
